name: Docker Build & Push

#this trigger workflow

on:
  push:
    branches:
      - master

#this will exicute on vm or server of ubuntu

jobs:
  build:
    run-on: ubuntu-latest

#this are the job steps

    steps:
     - name: checkout code
       uses: actions/checkout@v3

     - name: set up Docker
       uses: docker/setup-buildx-action@v3


     - name: Build Docker Image
       run: docker build -t github-action-flask .

     - name: Run Container
       run: docker run -d -p 5000:5000 github-actions-flask   
