name: Docker Build & Push

# this triggers the workflow
on:
  push:
    branches:
      - master

# this will execute on a VM or server with Ubuntu
jobs:
  build:
    runs-on: ubuntu-latest

    # these are the job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t github-actions-flask .

      - name: Run Container
        run: docker run -d -p 5000:5000 github-actions-flask

